language: java

jdk:
  - oraclejdk8

before_install:
  - mysql -e "create database IF NOT EXISTS economic_updater;" -uroot

install: true

services:
  - mysql

before_script:
  - mvn install -q -U -DskipTests=true -Dmaven.test.redirectTestOutputToFile=true || true
  - mvn install -q -U -DskipTests=true -Dmaven.test.redirectTestOutputToFile=true

script: mvn install -q -nsu -Dmaven.test.redirectTestOutputToFile=true -P '!integration'

after_success:
  - coveralls